### ISSUE TITLE
[Compatibility] Twilight Forest

### ISSUE THREAD

**Issue by sa-shiro** [orangeadam3/terra121#10]
Mod seems to be incompatible with TF Biomes
log:
https://paste.dimdev.org/ohudemevug.mccrash

**Comment by orangeadam3** [comment]
It seems like they do some strange replacement of the biome provider. There might be a way to allow my mod to support other providers, I can look into it but it might be strange if the biome type doesn't match earth.

**Comment by orangeadam3** [comment]
Ok, I pushed an edit to not force my biome provider so it *shouldn't* crash now. It might have some wacky side effects with the mod (trees probably won't spawn right), but feel free to try with the latest commit.

**Comment by sa-shiro** [comment]
ok ill have a look at it, thanks :)

**Comment by sa-shiro** [comment]
https://paste.dimdev.org/ivohayiyod.mccrash

is still present somehow
btw ignore the 180 mods hehe :D it works if i disable TF

**Comment by orangeadam3** [comment]
Oh sorry, I'm having trouble with git, I could have sworn I committed those changes but now I think I have.

**Comment by sa-shiro** [comment]
Had no time to test it, gonna test it now, if its working

**Comment by sa-shiro** [comment]
Issue is fixed, thanks for your work! :)
